import Footer from "@/components/footer/Footer";
import "./globals.css";
import Navigation from "@/components/navigation/Navigation";
import { Inter, Bebas_Neue } from "next/font/google";

export const metadata = {
  title: "Rebuilding Lives",
  description: "Generated by create next app",
};

export const inter = Inter({
  display: "swap",
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-inter",
});

const bebas = Bebas_Neue({
  display: "swap",
  style: ["normal"],
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-bebas",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${bebas.variable}`}>
      <body className="relative">
        <Navigation />
        <div className="w-3/4 mx-auto h-[1px] bg-gray-300"></div>
        {children}
        {/* <main>{children}</main> */}
        <Footer />
      </body>
    </html>
  );
}
